### ISSUE TITLE
no longer works

### ISSUE THREAD

**Issue by BlueXAyman** [Fuwn/soyuz#2]
this no longer works, is it possibly maybe that you can update it?

**Comment by Fuwn** [comment]
~What kind of logs does Soyuz emit during execution?~

Looks like at some point the Lunar Client changed the base name of their window to include the current Minecraft version. I've updated Soyuz to account for that. Soyuz seems to work fine under my testing.

**Comment by BlueXAyman** [comment]
could you maybe put it in releases, i dont have a C++ compiler
