### ISSUE TITLE
request

### ISSUE THREAD

**Issue by BlueXAyman** [Fuwn/soyuz#3]
hi man, idk if the comment i made on a closed issues sends you a notification, but i cant build for some reaon, ive tried but most likely im doing something wrong..
do you think you can maybe give me a link to the built exe or put it in releases please?

thanks.

**Comment by Fuwn** [comment]
Sure. Release `1.1.4` is now in the [Releases](https://github.com/Fuwn/soyuz/releases/tag/1.1.4).
